# -*- mode: ruby -*-
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  # Namenode stuff
  config.vm.define "namenode" do |namenode|
    namenode.vm.hostname = "namenode"
    namenode.vm.network "private_network", ip: "192.168.33.10"
    namenode.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  # Data nodes
  config.vm.define "datanode-01" do |dnode1|
    dnode1.vm.hostname = "datanode-01"
    dnode1.vm.network "private_network", ip: "192.168.33.21"
    dnode1.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.define "datanode-02" do |dnode2|
    dnode2.vm.hostname = "datanode-02"
    dnode2.vm.network "private_network", ip: "192.168.33.22"
    dnode2.vm.provision "ansible" do |ansible|
      ansible.playbook = "playbook.yml"
    end
  end

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end
end
